#!/bin/bash

# 创建目录结构
mkdir -p R
mkdir -p src/ciam-fast
mkdir -p inst/extdata
mkdir -p man
mkdir -p tests/testthat
mkdir -p benchmarks/mdv-benchmark
mkdir -p experiments/{01-ood-generalization/results,02-few-shot,03-ablation,04-efficiency}
mkdir -p models/{pretrained,model-cards}
mkdir -p data/{medical-sample,industrial-sample}
mkdir -p data-raw
mkdir -p paper
mkdir -p figures/generated
mkdir -p docker
mkdir -p docs
mkdir -p vignettes

# 创建 README.md
cat > README.md << 'EOF'
[将你文档中 README.md 的内容粘贴到这里]
EOF

# 创建 .gitignore
cat > .gitignore << 'EOF'
[将你文档中 .gitignore 的内容粘贴到这里]
EOF

# 创建 CITATION.cff
cat > CITATION.cff << 'EOF'
[将你文档中 CITATION.cff 的内容粘贴到这里]
EOF

# 创建 Dockerfile
cat > docker/Dockerfile << 'EOF'
[将你文档中 Dockerfile 的内容粘贴到这里]
EOF

# 创建 DESCRIPTION 文件
cat > DESCRIPTION << 'EOF'
Package: AdaptVisR
Title: Causal Intervention Attention Mechanism for Trustworthy Visual Recognition
Version: 1.0.0
Authors@R: c(
    person("Chen", "Ye", role = c("aut", "cre"), email = "chen.ye@example.com"),
    person("Xiaoqun", "Qin", role = "aut")
  )
Description: Full-stack adaptive learning system implementing Causal Intervention 
    Attention Mechanism (CIAM) for trustworthy visual recognition under domain shift.
License: MIT + file LICENSE
Encoding: UTF-8
LazyData: true
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.2.3
Imports:
    torch,
    reticulate,
    keras,
    tensorflow,
    shapviz
Suggests:
    testthat (>= 3.0.0),
    knitr,
    rmarkdown
EOF

# 创建 NAMESPACE 文件
cat > NAMESPACE << 'EOF'
# Generated by roxygen2: do not edit by hand
export(ciam_model)
export(causal_intervention)
export(meta_select)
export(evaluate)
importFrom(torch, torch_tensor)
importFrom(reticulate, import)
EOF

echo "仓库结构创建完成！"
